### ISSUE TITLE
Tutorial/Wiki Pages Contain Spelling/Grammar Mistakes

### ISSUE THREAD

**Issue by byteknacker** [rsksmart/tutorials#10]
I am not sure how to make changes or make a Pull Request to edit the errors on the Wiki pages within this project but I noticed lots of grammar and spelling mistakes in English whilst translating the tutorial into Chinese. 

Please advise me on how to edit the Wiki pages of this tutorial.

Thank you.

**Comment by alepc253** [comment]
Changed, let us know if you see any other mistake
