### ISSUE TITLE
react needs to be installed locally for the DAPP to work

### ISSUE THREAD

**Issue by quiquee** [rsksmart/tutorials#6]
I have tried in two different brand new setups and I always needed to do npm install react in the frontend-app for it to work. Otherwise it fails with an error in the require react

**Comment by quiquee** [comment]
Failed to compile

./src/index.js
Module not found: Can't resolve 'react' in '/home/enrique/tutorials/tutorials2/ChildrenWallet/frontend-app/src'

This error occurred during the build time and cannot be dismissed.

**Comment by aitoribanez** [comment]
React package is on package.json defined as dependency. So, typing 'npm install' or 'npm i' inside frontend-app folder, should work.

**Comment by quiquee** [comment]
Well it didnt, twice. I will debug it and let you know

**Comment by herrerameri** [comment]
Hello @quiquee ! You should run the `npm install` command positioned into `frontend-app` folder.
Please tell me know if you could try it.

**Comment by quiquee** [comment]
I could not reproduce it again. npm install was not installing react , that happened to me in 2 computers, but I tried in a docker image and in another computer and I did not have the problem again

**Comment by quiquee** [comment]
I think this is the result of the behaviour of npm install which didnt
assume --save option until a recent version ...
I came across the same issue yesterday for another project and that was the
reason

**Comment by aitoribanez** [comment]
--save is used to save the package as a package.json dependency. As react is installed as a dependency, typing npm install, react package is installed.

On Santander presentation I guide, when I tried to run the (react) dapp, I got an error because npm dependencies was not installed. npm install and (react) dapp went fine, without any error.

My two cents! ;-)
