### ISSUE TITLE
var myAccount = web3.eth.coinbase; returns undifined 

### ISSUE THREAD

**Issue by tehsunnliu** [rsksmart/tutorials#7]
Hello. I'm completely new to this and wanted to learn about rsk. I reached Module 5 with no problem. However, in Module 5 there's a code `var myAccount = web3.eth.coinbase;` which is supposed to return an address but in my case it's returning "undefined" and when I try `myAccount` it returns "0x00". I don't know whats wrong I'm doing? I setup rsk for testnet with the following `truffle.js` configuration

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
	networks: {
		development: {
			host: "localhost",
			port: 4444,
			network_id: "*"	// Match any network id
		}
	}
};
```

Sorry If I'm asking this in the wrong place. I've no idea where to ask questions.
Really appreciate your help. 
Thank you.

**Comment by herrerameri** [comment]
Hello @tehsunnliu and thanks for your reporting! 
It was a mistake in the wiki page.
Please, check it now, it's updated.
Any doubt, please don't hesitate to contact us in our chat room in Gitter -> https://gitter.im/rsksmart/rskj.
