### ISSUE TITLE
Tutorial Module 0 Has Broken Links

### ISSUE THREAD

**Issue by byteknacker** [rsksmart/tutorials#9]
After inspection, the links at the bottom are broken or lead to unexpected locations.

"Have a look at this transaction in the RSK Testnet: 0x1e7df6b62afde0d369ef00b727667c20f08a0c1924fceeee6d7642f5a0fc8488. This transaction deploys an ERC20 token contract in 0x3b195d8b76129cc21f90841c55a8b118492bb490 address. In the transactions tab we can find many executions of the send method of the token."

The first link is https://explorer.testnet.rsk.co/tx/0x1e7df6b62afde0d369ef00b727667c20f08a0c1924fceeee6d7642f5a0fc8488 

but there is no transaction found for the transaction has of 0x1e7df6b62afde0d369ef00b727667c20f08a0c1924fceeee6d7642f5a0fc8488

Furthermore, the ERC 20 token address 0x3b195d8b76129cc21f90841c55a8b118492bb490 does not display the expected transaction methods being used. 

https://explorer.testnet.rsk.co/address/0x3b195d8b76129cc21f90841c55a8b118492bb490?tab=transactions

The possible reason for this issue is that the links used to point to the right transaction but the RSK Testnet may be reinitiated or otherwise changed and now it does not show the appropriate example. 

Since this is a tutorial for beginners or new interested developers to get to know RSK, it is good to have it point to the correct resource lest they lose initial interests.

Attached are screenshots of the problems. 

Solution: make another Testnet example and link it to the appropriate locations in the tutorial text. 

![transaction not found](https://user-images.githubusercontent.com/10653912/47290931-02cbf600-d602-11e8-8884-1ba1a76365cd.jpg)
![transaction doesnt match](https://user-images.githubusercontent.com/10653912/47290933-03648c80-d602-11e8-90be-dcc8477784d4.jpg)

**Comment by alepc253** [comment]
Thanks! Changed
